# Generated by Django 4.2.13 on 2026-03-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('clicked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Raw IP of the visitor. Used for geo-resolution and abuse detection.', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Full User-Agent string for device/browser analytics.', null=True)),
                ('referer', models.URLField(blank=True, help_text='HTTP Referer header — where the click originated from.', max_length=2048, null=True)),
                ('country', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 country code, resolved from IP asynchronously.', max_length=2, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'clicks',
                'ordering': ['-clicked_at'],
            },
        ),
    ]
