# Generated by Django 4.2.13 on 2026-03-07 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='click',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='shortener.url'),
        ),
        migrations.AddIndex(
            model_name='click',
            index=models.Index(fields=['url', 'clicked_at'], name='idx_url_clicked_at'),
        ),
        migrations.AddIndex(
            model_name='click',
            index=models.Index(fields=['url', 'country'], name='idx_url_country'),
        ),
    ]
