# Generated by Django 4.2.13 on 2026-03-07 10:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_url', models.TextField(help_text='The full destination URL.')),
                ('short_code', models.CharField(db_index=True, help_text='Auto-generated unique slug used in the short URL.', max_length=10, unique=True)),
                ('custom_alias', models.CharField(blank=True, db_index=True, help_text='Optional user-defined alias. Overrides short_code if set.', max_length=50, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='If set, redirects will fail after this datetime.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Deactivate to stop redirects without deleting the record.')),
            ],
            options={
                'db_table': 'urls',
                'ordering': ['-created_at'],
            },
        ),
    ]
