# Generated by Django 4.2.13 on 2026-03-07 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Null for anonymous/public URL creation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='url',
            index=models.Index(fields=['short_code', 'is_active'], name='idx_short_code_active'),
        ),
        migrations.AddIndex(
            model_name='url',
            index=models.Index(fields=['custom_alias', 'is_active'], name='idx_alias_active'),
        ),
    ]
